name: Deploy to GitHub Pages
on:
  push:
    branches: 'main'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18.x
      - name: npm install and build
        env:
          BASE_PATH: '/fidget'
          MODEL_URL: '/GoodGrief'
        run: |
          npm install
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/'

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./
          TARGET_DIR: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
